version: "3.3"

networks:
  traefik-proxy:
    name: traefik-proxy

services:
  frontend-dev:
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    container_name: music-functions-frontend-dev
    networks:
      - traefik-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.music-functions-frontend-dev.rule=Host(`${DEVELOPMENT_DOMAIN}`)"
      - "traefik.http.routers.music-functions-frontend-dev.entrypoints=websecure"
      - "traefik.http.routers.music-functions-frontend-dev.tls.certresolver=${ACME_CERT_RESOLVER}"
      - "traefik.http.middlewares.music-functions-dev-ipwhitelist.ipwhitelist.sourcerange=${DEVELOPER_IP_SOURCERANGE}"
      - "traefik.http.routers.music-functions-frontend-dev.middlewares=music-functions-dev-ipwhitelist@docker"
    volumes:
      - ${DEVELOPMENT_MOUNTED_VOLUME}/frontend:/app

  api-dev:
    build:
      context: api
    container_name: music-functions-api-dev
    networks:
      - traefik-proxy
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.music-functions-api-dev.rule=Host(`${DEVELOPMENT_DOMAIN}`) && (PathPrefix(`/api/`) || Path(`/docs`) || Path(`/openapi.json`))"
      - "traefik.http.routers.music-functions-api-dev.entrypoints=websecure"
      - "traefik.http.routers.music-functions-api-dev.tls.certresolver=${ACME_CERT_RESOLVER}"
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80", "--reload"]
    volumes:
      - ${DEVELOPMENT_MOUNTED_VOLUME}/api/app:/code/app
